* Xciao
X ClassName In And Out

Transform one key press in to another for specific X windows only.

*** Why?
Some applications have horrible keybinds and no way to configure them.

*** But xdotool...
In the context of using xdotool with sxhkd, xdotool very often requires a vast
array of hacks/workarounds to work. sleep 0.2, --delay, --clearmodifiers,
spamming the keys, @release. These workarounds can even be application dependent.
https://github.com/baskerville/sxhkd/issues?q=xdotool

*** But extensions...
In regards to browsers, extensions have a number of limitations.

1. Loading pages block extensions.
   Accidentally navigate to a page you don't want? Too bad, you have to wait for
   it to load before going back.

2. Extensions are unavailable on some pages.
   Accidentally open new tab?
   Find yourself on the History page?
   What about Downloads?
   You're now stranded, forced to do the unthinkable, use the mouse!

*** How?
Our only hope is to make the good keybindings produce the bad keybindings.


** Setup

#+begin_src c
   /* xciao.c */

   static Remap remaps[] = {
  /*   Class  | Input mask  | Input key | Output mask | Output key */
   {"Chromium","ControlMask",    "k"    ,"ControlMask", "Next"} /* ctrl-k -> Next Tab */
   {"Chromium","Mod1Mask",       "k"    ,     ""      , "Up"}   /* alt-k -> Up arrow key */
   };
#+end_src

#+begin_src sh
  # sxhkd

  # Next tab
  control + k
      xciao "ControlMask" "k"

  alt + k
      xciao "Mod1Mask" "k"

 #+end_src

** Resources
[[https://github.com/gonzaru/dwm][Gonzaru 'no patch' DWM functions:]] Legendary resource for dwm and xlib programming. (fakepresskey, getwindowclass)
