* XCIAO (WIP)

X Classname In And Out

Turn one keypress in to another for specific X window

*** Say 'ciao' to terrible default keybinds
Native keybinds in programs like Chrome and Firefox are TERRIBLE.

Do people actually use keybinds like:

#+begin_src shell
Control + Tab, Control + Shift + Tab
#+end_src

My hands feel cramped just reading that

*** How?
If the classname of the current window matches the one passed in as an argument,
xciao will prodouce the 'Out' key, else it will prodouce the 'In' key
#+begin_src shell
  #                     The key you press       The key it produces
  #        Classname    Modifier       key       Modifier   key
  xciao "Brave-browser" "Control" "bracketleft" "Mod1Mask" "Left"
#+end_src

*** Use a tool like sxhkd with xciao to fix these egregious keybinds
**** Brave-browser

Extensions like vimium and surfingkeys are execellent tools for re-mapping keys
to more comfortable alternatives.

However, browser extensions have limitations.

1. Some pages do not have access to extensions such as History, Bookmarks and Downloads pages.
2. Pages must load extensions, if a pages is having trouble loading, you must wait for it.

Re-mapping native keybinds overcomes these limitations

#+begin_src shell
# Brave-browser
  control + j # Previous tab
      xciao "Brave-browser" "ControlMask" "j" "ControlMask" "Prior"

  control + k # Next tab
      xciao "Brave-browser" "ControlMask" "k" "ControlMask" "Next"

  control + d # Scroll down half page
      xciao "Brave-browser" "ControlMask" "d" "" "Next"

  control + u # Scroll up half page
      xciao "Brave-browser" "ControlMask" "u" "" "Prior"

  alt + h # Left arrow key
      xciao "Brave-browser" "Mod1Mask" "h" "" "Left"

  alt + j # Down arrow key
      xciao "Brave-browser" "Mod1Mask" "j" "" "Down"

  alt + k # Up arrow key
      xciao "Brave-browser" "Mod1Mask" "k" "" "Up"

  alt + l # Right arrow key
      xciao "Brave-browser" "Mod1Mask" "l" "" "Right"

  control + bracketleft # Forward browser history
      xciao "Brave-browser" "Control" "bracketleft" "Mod1Mask" "Left"

  control + bracketright # Backwards browser history
      xciao "Brave-browser" "Control" "bracketright" "Mod1Mask" "Right"
#+end_src

*** Limitations
This is very much a quick and dirty implementation that barely meets my own needs, and thus suffers from many
limitations.

**** Problems
1. Keybinds are limited to a single command
2. Commands are limited to a single class
